package com.qsoft.kata5.ui.view;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.qsoft.kata5.ui.control.MainController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * User: Admin
 * Date: 8/16/13
 * Time: 9:01 AM
 */
public class MainWindow extends JFrame
{
    public static final String MAIN_WINDOW_NAME = "mainWindow";
    public static final String BTN_STARTGAME = "btnStartGame";
    public static final String BTN_ENDGAME = "btnEndGame";
    public static final String LB_STATUS = "lbStatus";
    public static final String STT_STARTED = "GAME STARTED !";
    public static final String STT_ENDED = "GAME ENDED !";
    public static final String STT_DRAWED = "GAME DRAWED !";
    public static final String STT_XWON = "X WON !";
    public static final String RDB_X = "rdbX";
    public static final String RDB_O = "rdbO";
    public static final int MAX_ROW = 3;
    public static final int MAX_COL = 3;
    private JPanel mainPanel;
    private JPanel controlPanel;
    private JButton btnStartGame;
    private JButton btnEndGame;
    private JLabel lbStatus;
    private JPanel caroPanel = new JPanel(new GridLayout(MAX_ROW, MAX_COL));
    private JRadioButton oRadioButton;
    private JRadioButton xRadioButton;
    ;
    private Cell[][] cells = new Cell[MAX_ROW][MAX_COL];

    public MainWindow(final MainController mainController)
    {
        super(MAIN_WINDOW_NAME);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        pack();
        setName(MAIN_WINDOW_NAME);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        btnStartGame.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                mainController.doStartGame();
            }
        });

        btnEndGame.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                mainController.doEndGame();
            }
        });
    }

    public JLabel getLbStatus()
    {
        return lbStatus;
    }

    public Cell[][] getCells()
    {
        return cells;
    }

    public JPanel getCaroPanel()
    {
        return caroPanel;
    }

    private void createUIComponents()
    {
        btnStartGame = new JButton();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:12px:noGrow,left:200dlu:noGrow,fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:340px:noGrow"));
        mainPanel.setFont(new Font("Vladimir Script", Font.BOLD, 18));
        mainPanel.setName("lbStatus");
        lbStatus = new JLabel();
        lbStatus.setFont(new Font("DialogInput", Font.BOLD, 16));
        lbStatus.setName("lbStatus");
        lbStatus.setText("WELCOME TICTACTOE !");
        lbStatus.setVerticalAlignment(0);
        lbStatus.setVerticalTextPosition(0);
        CellConstraints cc = new CellConstraints();
        mainPanel.add(lbStatus, cc.xyw(1, 1, 2, CellConstraints.CENTER, CellConstraints.DEFAULT));
        controlPanel = new JPanel();
        controlPanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        mainPanel.add(controlPanel, cc.xy(3, 1));
        btnStartGame.setName("btnStartGame");
        btnStartGame.setText("START GAME");
        controlPanel.add(btnStartGame, cc.xy(1, 1));
        btnEndGame = new JButton();
        btnEndGame.setName("btnEndGame");
        btnEndGame.setText("END GAME");
        controlPanel.add(btnEndGame, cc.xy(1, 3));
        caroPanel.setPreferredSize(new Dimension(700, 600));
        mainPanel.add(caroPanel, cc.xywh(2, 3, 1, 9, CellConstraints.FILL, CellConstraints.FILL));
        caroPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null));
        oRadioButton = new JRadioButton();
        oRadioButton.setName("rdbX");
        oRadioButton.setText("O");
        mainPanel.add(oRadioButton, cc.xy(3, 9, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setText("PLAY FIRST");
        mainPanel.add(label1, cc.xy(3, 5, CellConstraints.CENTER, CellConstraints.DEFAULT));
        xRadioButton = new JRadioButton();
        xRadioButton.setName("rdbO");
        xRadioButton.setText("X");
        mainPanel.add(xRadioButton, cc.xy(3, 7, CellConstraints.CENTER, CellConstraints.DEFAULT));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(xRadioButton);
        buttonGroup.add(oRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }
}
