package com.qsoft.kata5.ui.view;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.qsoft.kata5.ui.control.MainController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * User: Admin
 * Date: 8/16/13
 * Time: 9:01 AM
 */
public class MainWindow extends JFrame
{
    public static final String MAIN_WINDOW_NAME = "mainWindow";
    public static final String BTN_STARTGAME = "btnStartGame";
    public static final String BTN_ENDGAME = "btnEndGame";
    public static final String LB_STATUS = "lbStatus";
    public static final String STT_STARTED = "GAME STARTED !";
    public static final String STT_ENDED = "GAME ENDED !";
    private JPanel mainPanel;
    private JPanel controlPanel;
    private JButton btnStartGame;
    private JButton btnEndGame;
    private JLabel lbStatus;

    public MainWindow(final MainController mainController)
    {
        super(MAIN_WINDOW_NAME);
        setSize(800, 600);
        setName(MAIN_WINDOW_NAME);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setContentPane(mainPanel);

        btnStartGame.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                mainController.doStartGame();
            }
        });

        btnEndGame.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                mainController.doEndGame();
            }
        });
    }

    public JLabel getLbStatus()
    {
        return lbStatus;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:noGrow,left:320dlu:noGrow,fill:d:grow", "center:d:noGrow"));
        mainPanel.setFont(new Font("Vladimir Script", Font.BOLD, 18));
        mainPanel.setName("lbStatus");
        lbStatus = new JLabel();
        lbStatus.setFont(new Font("DialogInput", Font.BOLD, 16));
        lbStatus.setName("lbStatus");
        lbStatus.setText("WELCOME TICTACTOE !");
        lbStatus.setVerticalAlignment(0);
        lbStatus.setVerticalTextPosition(0);
        CellConstraints cc = new CellConstraints();
        mainPanel.add(lbStatus, cc.xyw(1, 1, 2));
        controlPanel = new JPanel();
        controlPanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        mainPanel.add(controlPanel, cc.xy(3, 1));
        btnStartGame = new JButton();
        btnStartGame.setName("btnStartGame");
        btnStartGame.setText("START GAME");
        controlPanel.add(btnStartGame, cc.xy(1, 1));
        btnEndGame = new JButton();
        btnEndGame.setName("btnEndGame");
        btnEndGame.setText("END GAME");
        controlPanel.add(btnEndGame, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }
}
